PROGRAMS = (
    ('DDC', 'Computer Science Double Degree'),
    ('DDM', 'Mathematics Double Degree'),
    ('ITM', 'IT Management'),
    ('MEC', 'Mathematical Economics'),
    ('MPH', 'Mathematical Physics'),
    ('ACS', 'Actuarial Science'),
    ('CPM', 'Computational Mathematics'),
    ('CFM', 'Computing & Financial Management'),
    ('FRM', 'Financial Analysis & Risk Management'),
    ('OPT', 'Mathematical Optimization'),
    ('STT', 'Statistics'),
    ('PRM', 'Pure Mathematics'),
    ('TCH', 'Math Teaching'),
    ('HON', 'Honours Mathematics'),
    ('COS', 'Computer Science'),
    ('MTS', 'Mathematical Studies'),
    ('BIO', 'Bioinformatics'),
    ('MFM', 'Mathematical Finance'),
    ('BUS', 'Business Administration'),
    ('COO', 'Combinatorics & Optimization'),
    ('APM', 'Applied Mathematics'),
    ('SCC', 'Scientific Computation'),
)
